#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: Faith in Femininity
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  A teen-led mission dedicated to giving impoverished women power over their periods.
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  By donating feminine products to local shelters, <em>Faith in Femininity</em> helps women in Flint, MI and surrounding areas maintain confidence, comfort and cleanliness. <em>Faith in Femininity</em> was formed through Fenton First Presbyterian Church by two high school students, <strong>Waverly Ritchie</strong> and <strong>Lindsey Gibb.</strong>  The mission is now in the process of becoming a 501(c)(3) non-profit organization.

#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: faithinfem@gmail.com
org_street_address: 501 S Leroy St #Please include suite number on the line below
org_address_suite:
org_city: Fenton
org_state: MI
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  48430
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  (810) 629-7801

#SOCIAL MEDIA
org_twitter_username: faithinfem
org_facebook_username: faithinfemininity
org_instagram_username: faithinfemininity

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
501c3: false

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: 
tinyletter_username: faithinfemininity

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: false

#THEME
#Select one of the five color schemes (default, one, two, three, or four)
theme: three

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0

plugins:
  - jekyll-seo-tag

title: Faith in Femininity Official Website
description: >
  A teen-led mission dedicated to giving impoverished women power over their periods.
logo: assets/img/Faith-resized.png
